---
- hosts: all
  user: root
  tasks:

    - name: user jenkins
      user: name=jenkins

    - name: download jenkins.repo
      get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
               dest=/etc/yum.repos.d/jenkins.repo
               mode=0440

    - name: rpm_key for jenkins
      rpm_key: state=present key=http://apt.sw.be/RPM-GPG-KEY.dag.txt

    - name: yum jenkins
      yum: name=jenkins state=latest


